version: '3.8'

services:
  app:
    build: .
    container_name: gdpr-user-registry
    network_mode: host
    ports:
      - "3000:3000"
    env_file:
      - .env

    volumes:
      - app-data:/app/data

    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: gdpr-user-registry-db
    environment:
      POSTGRES_DB: gdpr
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  app-data:
  pgdata: